name: Deploy to Azure - Demo

on:
  push:
    branches:
      - main

env:
    LOCATION: westeurope
    TEST_IMAGE_TAG: 'bs-${{ github.sha }}'
    DEPLOYMENT_BICEP_PATH: |
        infra/main.bicep
    DOCKERFILE_PATH: |
        ~/TechConnect-Repo/ContainerApp-AlbumAPI-.NET/src/Dockerfile
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
             
    - name: Set up Bicep CLI
      run: |
        az bicep install

    - name: Deploy Bicep template
      run: |
        az deployment sub create --location ${{ env.LOCATION }} --template-file ${{ env.DEPLOYMENT_BICEP_PATH }} 
     
    - name: Checkout code
      uses: actions/checkout@v2

    # Build and deploy the container app
    - name: Build and deploy Container App
      uses: ./
      with:
        appSourcePath: ${{ env.DOCKERFILE_PATH }}
        acrName: acrlpwpok2xmi6t6 
        acrUsername: acrlpwpok2xmi6t6
        acrPassword: ${{ secrets.ACR_PASSWORD }}
        containerAppName: acasrclpwpok2xmi6t6
        containerAppEnvironment: acaenvlpwpok2xmi6t6
        resourceGroup: TC2025RGDemo
        imageToBuild: acrlpwpok2xmi6t6.azurecr.io/${{ env.TEST_IMAGE_REPOSITORY }}:${{ env.TEST_IMAGE_TAG }}
        dockerfilePath: ${{ env.DOCKERFILE_PATH }} 