name: Deploy to Azure - Demo

on:
  push:
    branches:
      - main

env:
    RESOURCE_GROUP: TC2025RGDemo2
    WORKSPACE_NAME: tc2025workspacedemo
    APP_INSIGHTS_NAME: tc2025demo_appIn
    LOCATION: westeurope
    CONTAINER_APP_NAME: tc2025demo_acaenv
    DEPLOYMENT_BICEP_PATH: |
        infra/main.bicep
    TEST_IMAGE_TAG: 'bs-${{ github.sha }}'
    TEST_IMAGE_REPOSITORY: 'AlbumAPI'
    DOCKERFILE_PATH: |
        ~/TechConnect-Repo/ContainerApp-AlbumAPI-.NET/src/Dockerfile
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
             
    - name: Set up Bicep CLI
      run: |
        az bicep install

    - name: Deploy Bicep template
      run: |
        az deployment sub create --location ${{ env.LOCATION }} --template-file ${{ env.DEPLOYMENT_BICEP_PATH }} 

    - name: Set up Log Analytics Workspace
      run: |
        az monitor log-analytics workspace create --resource-group ${{ env.RESOURCE_GROUP }} --workspace-name ${{ env.WORKSPACE_NAME }} --location ${{ env.LOCATION }}

    - name: Set up Application Insights
      run: |
        az monitor app-insights component create --app ${{ env.APP_INSIGHTS_NAME }} --location ${{ env.LOCATION }} --resource-group ${{ env.RESOURCE_GROUP }} --application-type web

    - name: Set Application Insights Key
      id: get-app-insights-key
      run: |
        echo "::set-output name=APPINSIGHTS_INSTRUMENTATIONKEY::$(az monitor app-insights component show --app ${{ env.APP_INSiGHTS_NAME }} --resource-group ${{ env.RESOURCE_GROUP }} --query instrumentationKey --output tsv)"

    - name: Update environment variables
      run: |
        echo "APPINSIGHTS_INSTRUMENTATIONKEY=${{ steps.get-app-insights-key.outputs.APPINSIGHTS_INSTRUMENTATIONKEY }}" >> $GITHUB_ENV

    - name: Deploy Container App with Environment Variables
      run: |
        az containerapp update --name ${{ env.CONTAINER_APP_NAME }} --resource-group ${{ env.RESOURCE_GROUP }} --environment-variables ASPNETCORE_ENVIRONMENT=Development LOG_ANALYTICS_WORKSPACE_ID=$LOG_ANALYTICS_WORKSPACE_ID APPINSIGHTS_INSTRUMENTATIONKEY=${{ steps.get-app-insights-key.outputs.APPINSIGHTS_INSTRUMENTATIONKEY }}
