name: Deploy to Azure - Demo

on:
  push:
    branches:
      - main

env:
    LOCATION: westeurope
    TEST_IMAGE_TAG: 'bs-${{ github.sha }}'
    TEST_IMAGE_REPOSITORY: 'ContainerApp-AlbumAPI-.NET'
    DEPLOYMENT_BICEP_PATH: |
        infra/main.bicep
    DOCKERFILE_PATH: |
        ~/TechConnect-Repo/ContainerApp-AlbumAPI-.NET/src/Dockerfile
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
             
    - name: Set up Bicep CLI
      run: |
        az bicep install

    - name: Deploy Bicep template
      run: |
        az deployment sub create --location ${{ env.LOCATION }} --template-file ${{ env.DEPLOYMENT_BICEP_PATH }} 
     
    - uses: azure/docker-login@v2
      with:
          login-server: techconnect2025acr.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      
    - run: |
          docker build . -t techconnect2025acr.azurecr.io/${{ env.TEST_IMAGE_REPOSITORY }}:${{ env.TEST_IMAGE_TAG }}
          docker push techconnect2025acr.azurecr.io/${{ env.TEST_IMAGE_REPOSITORY }}:${{ env.TEST_IMAGE_TAG }}

    